# Generated by Django 3.1.7 on 2021-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alphacode2', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=200)),
                ('population', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=500)),
                ('neighbouring_countries', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
    ]
